apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WTrNYggOUKxH/Tb2PN9Enz8CfHC7kZFws4/CG6IqkSDMrpQi4deB/w==,iv:ABWsN9vayOgGd2I2j4uiwpefYqMg7O8us+sZMyAZ1s8=,tag:8pcLTKLye4MyUACLehvjUA==,type:str]
sops:
  age:
    - recipient: age19jj0zg8msfdhp2ay70z4jkdl5k4pqus3mprvy0hwhec3rygnm9qsfqq7lm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d1d1U2s0UGlFMXAwWjkz
        UHVtSm9ZTGdTcmlKQ2lodFcxZ2lmUEFaV1hZCisxbWNBcnhxVmpSMFlHazhtaDN0
        NkorSk5rVXpDZmExK05yd1Z3cjlSOUEKLS0tIENzYmhHUStsWlJTVW1qYVFCV05D
        OE1EYm83K2p1ZUNhSUNVTUVYVGg3RkkKT6/+kepxPnGSLlQEdN/u1p6TDrfYOKto
        FcRzXKbtdXR706T6v7+VuqVInSNkZlCe139HHWmTeknRLZ1e+Fd+iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T18:46:06Z"
  mac: ENC[AES256_GCM,data:JJgiVvxeC06xDWDsgD/kJv0fCXH1BnM7/IaQTUpt2WduO5ijJgIYN2dgmu/p1jywsCh2FHc+OFX06NBYRhKtSLIL0MnYx1/lvA4zJ0/p50pStS9ITp6A0COChlDJ/q2s84cPzBZEp1tJBDU8I6julsJrWFL6jGQMqDqNTyi9mZg=,iv:WmnNKyMFhieCKMnKnYIRLdsZtVAc4K3ciSByE6wbrZU=,tag:Z/TUzw/PrTE7OE5wwbGcbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
