apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:YB0Vb06Q5MnROyY=,iv:fMhnJf1VezAnTZxywpFaKWHIS6kRbbiSv1+8hlhFx/o=,tag:mU+cQPaaNBbjcrTAIbd4xQ==,type:str]
sops:
  age:
    - recipient: age19jj0zg8msfdhp2ay70z4jkdl5k4pqus3mprvy0hwhec3rygnm9qsfqq7lm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYzFaL1pmRkJHb0dUbGE4
        cDVYdjdKTDB3djJ5c2N5cGdObW50WFpjcUU4CkRKMjhveVNnOU5iZTUvLy8xU2dh
        MFM3bkdiQzcxdzRMUklLdFRlOWU0cW8KLS0tIEFpOFNXcjhzbXQzVk5qTW1xQS81
        ZlliK1FiVHBOSmZUQkFRMUZ2Z1lRMUkKsib++gXJcUy4Aiaw75V4tA1O8mZFOYDg
        3isn37wvenXH/gQUvLxZ1BDfVHIaQn+v/G4YV5jjv/g9a0edmKjsNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T18:46:06Z"
  mac: ENC[AES256_GCM,data:IDG5DYOOSiSqi59ekwk7hdIDaxn9cI8puN/ufSiIJBuD49Abv7QtP3YMYpQuA9fwjsuP2Bn44kenhZ6LIuNh4BMhg0WYLKSNRAq2V04b+m9LgT9+HV2imaM5h+qZ6AnEfOaywcc/INYPKTKGpqu5e4cO50P3BvsFFWojTlZBAlk=,iv:ogKdf3b0RIvfSix31aAcIY2HiL7Z+ayHrup4nkrJN74=,tag:TJR5fSfC+5hH5qTkngjDAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
