apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DCCqiAwhR32yQT/Eyn/Ya0EoAjos8J8cdcS3C437k4c=,iv:q3u23yzK8Wl1RUfjhRarmBi5PVW9e0dA4a1zOnSHLYc=,tag:+FOPSGvGHF8HkJYTSewRkg==,type:str]
sops:
  age:
    - recipient: age19jj0zg8msfdhp2ay70z4jkdl5k4pqus3mprvy0hwhec3rygnm9qsfqq7lm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV3N1UzNadE5aL1hOejRR
        UUxtemIrcjd6bDZoQk9OKzJuaHdGTEg0LzE4CmFHcXdodVJPeEp6UWhleU5KMmJk
        WkV1S0xRY0pqYXhpYUl5K2NiUFB4M1kKLS0tIFZBRDA1TDZzMUNyZ2V2WWs2Wlov
        dnNEN0oraEt4cVowMEJSYXZWWERaaFEKatmGFKXzrjH15T/Wxnd8ODnwZwClD/9O
        lT3Hbvv1s6tU50XygdJkNUsy/AEvGMR/2og8ejBVZ8Uz2dH40UtcLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T18:46:06Z"
  mac: ENC[AES256_GCM,data:00dR3CnHuJetjoUatvxavRZGNQdFBJwKS17/tahMQwUGtZp6fiHL0fZC5pM3/revWaztZ9v5d5Nfq7JaVlBnGOzQAtZXLxbjy1Jbk9QHMiq4zyNRlVpTxH/pDgz6BM7xkRU0nZw0Bwq0FMqaWeF26y5W7L/qJ7OpuRxqEd44178=,iv:zxW2XEG6Ht087OUHeGVIQau59aFIguEe9naqL+N1WVw=,tag:ei2me4lkp/FuOga5UhelUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
