apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Z7hyhDEv5Z3ZbDp1vhqOKZqqfUOaMuhxpLcqS5u+xPrgM/tsxx42LbOYQnOKFSNp9a2gSVlsvd4OAaqU6/x7jxg3MvYrRrrOWRojEZWdCf5Vlz4lDhdEJmYpgIEni1J7F9EefRzk9Q7fub0h0X3ACQI5k6ywRf4Zr1xO3+2wqjnBg4d9WbT8HLPcaZ9jxPsIutKMaMRx3jruAZbfDCS888KvATvtCxZqRe4286n2xfwMVCCG,iv:wNHId7xY09auHMfLkHoEYv8gQnKVE2yNeDLbPQXmad8=,tag:tZ7Rf+j/mLRV13yzsOh02g==,type:str]
sops:
  age:
    - recipient: age19jj0zg8msfdhp2ay70z4jkdl5k4pqus3mprvy0hwhec3rygnm9qsfqq7lm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYnIzcVVzRHZwTlBTZTBP
        OXlEY3NZS3B0Z2ZBNVdNczcxK2RNWGNlcDM0CnNwZVhobG0wTXA5cmtLQWFGbXNL
        UlNuNHNTeTRBNE9XWXJzTG1BY3gvTmcKLS0tIHc0Vy9waWp4SDJoOFgzZkNCKzRH
        T0pYajVwYTFhY1pxS0p6cVN2aXRLMncKhzE4gg1pb4V9ME2t5gLYeQznHoJBhJTM
        3C07KlfeW3EQ4UXGvHIgTYOKZWK59NcXQFJwbpI0C20v7XWtAD00KQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T18:46:06Z"
  mac: ENC[AES256_GCM,data:pU/SBol8ZEfJbYuNKWYtSKvaIAklPShZmDQaKZwvVXKe1P/CbC29vo+HP5SMDlT5eEGTUd2mAbZZbbrxrCrCdH9YX/jGgHut/4lEcf9xCiR48hizvISfee2wKwqhQj/01qVAE/DdvTubHA0PQHVGwtGra6nSSLRZKgnR+biRd0U=,iv:tQGJ4xUXP9PWYAVVkdP4HJR06LBBFf+MME/lhfWiHnY=,tag:VnjFdbxke+r9Xw5oHDrbTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
