---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  interval: 6h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ">=1.15.0"
  url: oci://docker.io/1password/connect-helm-charts/connect
