apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YhQg9FNsiWZx5qYTAFYw0YTC0TThS9ZDlxfaEZm1d2RmQgbk2gTTZA==,iv:wmJTGN9yXd+ldc8fSn/RwFBAgNxZKaGq/UWnVeEheFE=,tag:C3Zs5cT6UuZuzptneIgEVg==,type:str]
sops:
  age:
    - recipient: age19jj0zg8msfdhp2ay70z4jkdl5k4pqus3mprvy0hwhec3rygnm9qsfqq7lm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaUYzQTJOYUNaM0lOZDhZ
        aFY3RVZxckszWmJhYWZHNTFnellDc243UEM4CnBXYXFUbUIxR2N5T0xld2J3SWVG
        ZzVtT2hrOXc4dDBaUnpMU2VxZHhZRnMKLS0tIHJ0TDB4c0YyRWJpNzlFbE9WdkJC
        bnUyQ1FySmRHbm9udXVCUWMyWW5VTjQK1em29mKe+RHebtKvPHOfdYzRCMqMEZH2
        RmpFC714QmkBaDNn7FTebaJTqeUtMKYDzoN4Tof+JvpZe2z/C3aUiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T18:46:06Z"
  mac: ENC[AES256_GCM,data:XwbhhoAfdEBozeVMpt2naoF5B6oZJYZ+Qf/Bce9+IqhslWILamcGbvcOmna3kr2C8cac9yDEtBI8if4r8kaRMglEyDfhgnL9nxKYIHjizeoZDN639AFxmIXVVkz3aOVTHiuynU3f+wiZVNj9jFEppBGu78GVcmKX0OnjQPHRKQc=,iv:mB/xagAJe6YfkgO8pg3JFmqTR0ML6+/62CSuiX+9J0M=,tag:7xBxz/iROLbw5nQWa51X5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
